apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: poc-argocd
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dotnet-kafka-subscriber
  namespace: argocd
spec:
  project: default # default project in argocd
  source:
    repoURL: https://github.com/Workquark/argocd-dotnet-kafka-subscriber-deploy.git
    targetRevision: HEAD
    path: deploy-manifests
  destination:
    server: https://kubernetes.default.svc # gke control plane url.Also, argocd can connect to cluster externally .So you can mention multiple clusters like - https://x.x.x.x (gke control plane ip)
    namespace: poc-argocd
  syncPolicy:
    syncOptions:
      - createNamespace=true
    automated:
      selfHeal: true # can configure webhook for getting rid of 3 minute delay. So that as soon as changes happen webhook triggers argocd to pull changes from repo.TODO: Investigate how.
      prune: true
